include:
  - file: "/console-pipeline/react-app-vitest.gitlab-ci.yml"
    project: "platform/pipelines-templates"
    ref: "master"

.docker-job:
  variables:
    COMMIT_SHA_FILEPATH: /etc/nginx/commit.sha

default:
  image: node:20-alpine

variables:
  IMAGE_NAME: team-flare/vite-typescript-react-template
